title: Sarah Guthals, PhD
description: Director of DevRel
twitter_username: drughtlas
github_username: drguthals
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
